sensors:
  - name: "MainBedroom"
    serial_number: 2930217056
    type: "WavePlus"
    sample_period: 10
    address: "A0:6C:65:46:5C:CB"
  - name: "Playroom"
    serial_number: "GVH5100_4E95"
    type: "GVH5100"
    sample_period: 10
  - name: "Kitchen"
    serial_number: "GVH5100_2144"
    type: "GVH5100"
    sample_period: 10
  - name: "Garage"
    serial_number: "GVH5100_713F"
    type: "GVH5100"
    sample_period: 10
  - name: "FamilyRoom"
    serial_number: "GVH5100_323D"
    type: "GVH5100"
    sample_period: 10
  - name: "EmmaBedroom"
    serial_number: "GVH5100_2B6D"
    type: "GVH5100"
    sample_period: 10
  - name: "LiamBedroom"
    serial_number: "GVH5100_2660"
    type: "GVH5100"
    sample_period: 10
  - name: "LiamSmartPlug"
    type: "Kasa"
    model: "KP125M"
    sample_period: 10
    address: "192.168.50.202"
  - name: "EmmaSmartPlug"
    type: "Kasa"
    model: "KP125M"
    sample_period: 10
    address: "192.168.50.239"
  - name: "PlayroomSwitch"
    type: "Kasa"
    model: "HS220"
    sample_period: 10
    address: "192.168.50.21"
  - name: "DiningRoomLight"
    type: "Kasa"
    model: "KS225"
    sample_period: 10
    address: "192.168.50.90"
  - name: "EmmaLights"
    type: "Kasa"
    model: "KS225"
    sample_period: 10
    address: "192.168.50.204"
  - name: "FamilyRoomLights"
    type: "Kasa"
    model: "HS220"
    sample_period: 10
    address: "192.168.50.242"
  - name: "GarageLights"
    type: "Kasa"
    model: "KS205"
    sample_period: 10
    address: "192.168.50.170"
  - name: "LiamLightSwitch"
    type: "Kasa"
    model: "HS220"
    sample_period: 10
    address: "192.168.50.154"
  - name: "LivingRoomLights"
    type: "Kasa"
    model: "KS225"
    sample_period: 10
    address: "192.168.50.88"
  - name: "BackyardSwitch"
    type: "Kasa"
    model: "EP40"
    sample_period: 10
    address: "192.168.50.173"
  - name: "TeslaWallConnector"
    type: "TeslaWallConnector"
    sample_period: 10
    address: "192.168.50.108"
  - name: "KitchenRefrigeratorPlug"
    type: "Kasa"
    model: "KP125M"
    sample_period: 10
    address: "192.168.50.155"
  - name: "GarageRefrigeratorPlug"
    type: "Kasa"
    model: "KP125M"
    sample_period: 10
    address: "192.168.50.207"
  - name: "zigbee2mqtt"
    type: "zigbee2mqtt"
    sample_period: 10
    address: "192.168.50.113:1883"
sift_environments:
  - name: gov
    enabled: true
    base_uri: "https://gov.grpc-api.siftstack.com"
    use_ssl: true
  - name: dev
    enabled: true
    base_uri: "https://grpc-api.development.siftstack.com"
    use_ssl: true
  - name: prod
    enabled: true
    base_uri: "https://grpc-api.siftstack.com"
    use_ssl: true
  - name: local
    enabled: false
    base_uri: "http://192.168.50.188:50051"
    use_ssl: false
